"""token expiration

Revision ID: fd2a693902f5
Revises: e7f5933a4a38
Create Date: 2022-03-23 22:04:13.086886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd2a693902f5'
down_revision = 'e7f5933a4a38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('token_expiration', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'token_expiration')
    # ### end Alembic commands ###
